name: Build Pre-Release
on:
  workflow_dispatch:

jobs:
  BuildPreRelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout mihomo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/ClashMetaForAndroid
          ref: main
          fetch-depth: 1
          submodules: true
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: patchs
          fetch-depth: 1
      - name: patch file
        run: |
          cd core/src/foss/golang/clash
          git apply $GITHUB_WORKSPACE/patchs/.github/patch/0001-http.patch
