name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: MetaCubeX/mihomo
          ref: Alpha
          fetch-depth: 1
  build:
    uses: ./.github/workflows/build.yml
